blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('Model','FormController@model');
Route::get('validation','FormController@validation');
Route::post('validation','FormController@validationPost');
Route::resource('/employee', 'EmployeeController');

blog/app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table="employees";
    protected $fillable = ['firstname','lastname','email','dob','phone','address'];
}

blog/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

blog/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

blog/app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;
use App\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Employee::all();
        return view('model', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

            return view('model');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'firstname' => ['required', 'max:50', 'string'],
            'lastname' => ['required', 'max:50', 'string'],
            'email' => ['required', 'string', 'email', 'max:255','unique:employees'],
            'dob' => ['required'],
            'phone' => ['required', 'numeric', 'digits:10'],
            'address' => ['required', 'max:255'],
        ]);

            Employee::create([
                'firstname'=>$request->firstname,
                'lastname'=>$request->lastname,
                'email'=>$request->email,
                'dob'=>$request->dob,
                'phone'=>$request->phone,
                'address'=>$request->address,
            ]);
        return redirect()->route('employee.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Employee::find($id);
        $data->delete();

        return redirect()->route('employee.index');
    }
}

blog/resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script type="text/javascript" src="{{asset('js/core/app.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/core/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/core/bootstrap.bundle.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/core/blockui.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/themes/bootbox.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/themes/components_models.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/themes/datables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/themes/datatables_basic.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/themes/select2.min.js')}}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{asset('js/jquery.js')}}"></script>

    <link href="css/styles.min.css" rel="stylesheet" type="text/css">
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
    <link href="css/layout.min.css" rel="stylesheet" type="text/css">
    <link href="css/components.min.css" rel="stylesheet" type="text/css">
    <link href="css/colors.min.css" rel="stylesheet" type="text/css">

    <title>Document</title>

</head>
<body>

<div class="container-fluid">
    <div id="modal_form_horizontal" class="modal fade" tabindex="-1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Horizontal form</h5>
                    <button type="button" class="close" data-dismiss="modal">×</button>
                </div>

                <form action="{{route('employee.store')}}" method="post" class="form-horizontal" id="form">
                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                    <div class="modal-body">
                        <div class="form-group row">
                            <label class="col-form-label col-sm-3">First name</label>
                            <div class="col-sm-9">
                                <input type="text" name="firstname" placeholder="Eugene" class="form-control">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-sm-3">Last name</label>
                            <div class="col-sm-9">
                                <input type="text" name="lastname" class="form-control">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-sm-3">Email</label>
                            <div class="col-sm-9">
                                <input type="text" name="email" placeholder="eugene@kopyov.com" class="form-control">
                                <span class="form-text text-muted">name@domain.com</span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-sm-3">Dob #</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" name="dob">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-sm-3">Phone #</label>
                            <div class="col-sm-9">
                                <input type="tel" name="phone" class="form-control">

                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-sm-3">Address line 1</label>
                            <div class="col-sm-9">
 <textarea rows="5" cols="5" class="form-control" placeholder="Enter your address here" name="address">
                        </textarea></div>
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn bg-primary">Submit form</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @yield('content')


</div>
</body>
</html>

blog/resources/views/model.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <div class="card col-lg-10 offset-1 mt-5">
            <div class="card-header header-elements-inline" style="background-color: white">
                <legend class="text-uppercase font-size-sm font-weight-bold">Employees Data</legend>
            </div>
            <div class="card-body">
                <div id="DataTables_Table_1_wrapper" class="dataTables_wrapper no-footer mt-2">
                    <div class="datatable-header">
                        <div id="DataTables_Table_1_filter" class="dataTables_filter"><label><span>Filter:</span> <input
                                    type="search" class="" placeholder="Type to filter..."
                                    aria-controls="DataTables_Table_1"></label></div>
                        <div class="dataTables_length" id="DataTables_Table_1_length"><label><span>Show:</span> <select
                                    name="DataTables_Table_1_length" aria-controls="DataTables_Table_1"
                                    class="select2-hidden-accessible" data-select2-id="4" tabindex="-1"
                                    aria-hidden="true">
                                    <option value="10" data-select2-id="6">10</option>
                                    <option value="25">25</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                </select><span class="select2 select2-container select2-container--default" dir="ltr"
                                               data-select2-id="5" style="width: auto;"><span class="selection"><span
                                            class="select2-selection select2-selection--single" role="combobox"
                                            aria-haspopup="true" aria-expanded="false" tabindex="0"
                                            aria-disabled="false"
                                            aria-labelledby="select2-DataTables_Table_1_length-k3-container"><span
                                                class="select2-selection__rendered"
                                                id="select2-DataTables_Table_1_length-k3-container" role="textbox"
                                                aria-readonly="true" title="10">10</span><span
                                                class="select2-selection__arrow" role="presentation"><b
                                                    role="presentation"></b></span></span></span><span
                                        class="dropdown-wrapper" aria-hidden="true"></span></span></label></div>
                    </div>
                    <div class="datatable-scroll">
                        <table
                            class="table  table-xs font-size-sm table-bordered table-hover  dataTables_pagination datatable-highlight dataTable datatable-save-state table-striped"
                            role="grid" id="DataTables_Table_1" aria-describedby="DataTables_Table_1_info">
                            <thead>
                            <tr>

                                <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="First Name: activate to sort column descending">First Name
                                </th>
                                <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="BIrthDate: activate to sort column descending">lastname
                                </th>
                                <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="GEnder: activate to sort column descending">email
                                </th>
                                <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="Address: activate to sort column descending">dob
                                </th>
                                <th class="sorting_asc" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="Mobile No activate to sort column descending">phone
                                </th>
                                <th class="sorting_asc" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="Desciption No activate to sort column descending">address
                                </th>

                                <th class="sorting_asc" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="Delete No activate to sort column descending">Delete
                                </th>
                                <th class="sorting_asc" aria-controls="DataTables_Table_1" rowspan="1"
                                    colspan="1" aria-sort="ascending"
                                    aria-label="Edit No activate to sort column descending">Edit
                                </th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $data)
                                <tr role="row" class="odd">

                                    <td class="sorting_1">{{$data->firstname}}</td>
                                    <td>{{$data->lastname}}</td>
                                    <td>{{$data->email}}</td>
                                    <td>{{$data->dob}}</td>
                                    <td>{{$data->phone}}</td>
                                    <td>{{$data->address}}</td>
                                    <td>
                                        <form method="post" class="delete_form" action="/employee/{{$data->id}}">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE"/>
                                            <button type="submit" class="btn btn-danger" data-id="{{$data->id}}"
                                                    id="deleteform">Delete
                                            </button>
                                        </form>
                                    </td>
                                    <td><a type="button" class="btn btn-success"
                                           href="#">Edit</a></td>

                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                        <div class="datatable-footer">

                            <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate"><a
                                    class="paginate_button previous" aria-controls="DataTables_Table_0" data-dt-idx="0"
                                    tabindex="0" id="DataTables_Table_0_previous">←</a><span><a
                                        class=" paginate_button current"
                                        aria-controls="DataTables_Table_0"
                                        data-dt-idx="1"
                                        tabindex="0">1</a><a
                                        class="paginate_button" aria-controls="DataTables_Table_0" data-dt-idx="2"
                                        tabindex="0">2</a></span><a class="paginate_button next disabled"
                                                                    aria-controls="DataTables_Table_0" data-dt-idx="3"
                                                                    tabindex="0" id="DataTables_Table_0_next">→</a>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                    data-target="#modal_form_horizontal">
                                Add<i class="icon-play3 ml-2"></i></button>
                        </div>
                    </div>
                </div>
        </div>

        <script>

            $(document).ready(function () {
                $('#deleteform').click(function (e) {
                    var id = $(this).val();
                    var url = "{{url('employee')}}";
                    var dturl = url + "/" + id;
                    $.ajax({
                        url: dturl,
                        type: "DELETE",
                        cache: false,
                        data: {
                            _token: '{{csrf_token()}}'
                        },
                        success: function (dataResult) {
                            var dataResult = JSON.parse(dataResult);
                            if (dataResult.statusCode == 200) {
                                $ele.fadeOut().remove();
                            }
                        }
                    });
                });
            });


        </script>
        <script type="text/javascript" src="{{asset('js/validation/jquery.validate.min.js')}}"></script>
        <script>
            $(document).ready(function () {
                $('#form').validate({
                    rules: {
                        firstname: {
                            required: true,
                            maxlength: 10,

                        },
                        lastname: {
                            required: true,
                        },
                        email: {
                            required: true,
                            email: true
                        },
                        dob: {
                            required: true,
                            date: true
                        },
                        phone: {
                            required: true,
                            minlength: 10,
                            maxlength: 10,
                            digits: true
                        },
                        address: {
                            required: true,
                            maxlength: 50

                        }

                    }
                });
            });
        </script>
@endsection